name: Languages Analysis

on:
  schedule:
    - cron: "0 */24 * * *" 
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: metrics-languages.svg
          # 核心配置
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: "percentage,bytes-size"
          plugin_languages_colors: github
          plugin_languages_aliases: true
          plugin_languages_threshold: 0.3%
          plugin_languages_categories: programming, markup
          # 关闭其他插件
          plugin_activity: no
          plugin_habits: no
          plugin_repositories: no
          plugin_contributors: no
